server:
  port: 8401

spring:
  application:
    name: alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务注册中心地址
    sentinel:
      transport:
        # 配置sentinel dashboard的地址
        dashboard: localhost:8085
        port: 8719
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848  #nacos的地址
            groupId: DEV_GROUP # 配置文件的分组
            #namespace: ${spring.application.name}  #命名空间的id
            dataId: sentinel-server8401  # 名字与在nacosc创建的持久化文件名一致
            data-type: json  #文件类型是json
            rule-type: flow  # 路由存储规则
# 图形化监控
management:
  endpoints:
    web:
      exposure:
        include: '*'