server:
  port: 8801
spring:
  application:
    name: cloud-stream-rabbitmq-provider8801

  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称。用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合过程
        output: #这个名字是一个通道的名称
          destination: exchange-msg  #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，
      binder: defaultRabbit #设置要绑定的消息服务的具体设置