server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://cloud-payment-service
          #          uri: http://localhost:8001         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh   #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://cloud-payment-service
          #          uri: http://localhost:8001          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/serverPort/**             #断言，路径相匹配的进行路由
            - After=2020-09-22T10:10:19.816+08:00[Asia/Shanghai] # 超过当前时间才可以进行访问
            - Cookie=cloud,guo  # 携带Cookie信息 localhost:9527/get/serverPort --cookie "cloud=guo"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://eureka7002.com:7002/eureka/
      #      单机版eureka
      defaultZone: http://eureka7001.com:7001/eureka/

