server:
  port: 9002
spring:
  application:
    name: alibaba-nacos-provider-payment9001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'